include_directories(${CMAKE_CURRENT_LIST_DIR})

file(GLOB_RECURSE COMMON_FILES
   ${CMAKE_CURRENT_LIST_DIR}/*.h
   ${CMAKE_CURRENT_LIST_DIR}/*.cpp
)

target_sources(${PROJECT_NAME} PRIVATE ${COMMON_FILES})